name = "Formal"
license = "MPL-2.0"
licenselink = "https://github.com/PiotrZPL/hugo-theme-formal/blob/main/LICENSE"
description = "Formal is a simple and elegant theme with lots of features."
homepage = "https://github.com/PiotrZPL/hugo-theme-formal"
demosite = "https://blist.vercel.app"
tags = ["Hugo", "theme", "blog", "modern", "responsive", "formal", "elegant", "simple"]
features = ["clean", "gallery", "minimal", "minimalist", "mobile", "personal", "responsive", "simple", "tailwind", "blog", "white"]
min_version = "0.82.1"

[author]
  name = "Piotr Lange"
  homepage = "https://piotrlange.de/"
