baseurl = "https://blist.vercel.app"
metaDataFormat = "yaml"
title = "Formal Hugo theme"
theme = "hugo-theme-formal"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "I'm Christopher Green"
      introSubtitle = "47 y/o senior developer interested in geography and history"
      introPhoto = "/profile.webp"
      logo = "/blist-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/en/blog/emoji-support/"
        weight = 4

  [languages.de]
    contentDir = "content/de" # Deutsch
    weight = 2
    languageName = "Deutsch"
    title = "Formal Hugo theme"
    [languages.de.params]
      introTitle = "Ich bin Christopher Green"
      introSubtitle = "47-jähriger Senior-Entwickler mit Interesse an Geografie und Geschichte"
      introPhoto = "/profile.webp"
      logo = "/blist-logo-de.png"
    [[languages.de.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.de.menu.main]]
        name = "Über mich"
        url = "page/about/"
        weight = 2

    [[languages.de.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3
        
  [languages.pl]
    contentDir = "content/pl" # Polish
    weight = 3
    languageName = "Polski"
    title = "Formal Hugo theme"
    [languages.pl.params]
      introTitle = "Nazywam się Christopher Green"
      introSubtitle = "47-letni senior-developer interesujący się geografią i historią"
      introPhoto = "/profile.webp"
      logo = "/blist-logo.png"
    [[languages.pl.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.pl.menu.main]]
        name = "O mnie"
        url = "page/about/"
        weight = 2

    [[languages.pl.menu.main]]
        name = "Tagi"
        url = "tags"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Christopher Green · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-emerald-300"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I work on everything coding and tweet developer memes"
  # Up to 5-6 profiles work well on mobile devices
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  #xing = "https://www.xing.com/profile/"
  github = "https://github.com/"
  #medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  #dribbble = "https://dribbble.com/"
  stackoverflow = "https://stackoverflow.com/"
  youtube = "https://www.youtube.com/c/"
  #instagram = "https://www.instagram.com/"
  #facebook = "https://www.facebook.com/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
